<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Analyse extends Model
{
    use HasFactory;
    protected $fillable=[


        'demande_credit_id',
        'nom_prenom_emprunteur',
        'qualite_emprunteur',
        'sexe_emprunteur',
        'nom_prenom_pere',
        'nom_prenom_mere',
        'nature_numero_piece_identite',
        'lieu_naissance_emprunteur',
        'date_naissance_emprunteur',
        'residence_actuelle_emprunteur',
        'nom_association',
        'employeur_emprunteur',
        'lieu_travail_emprunteur',
        'tel_emprunt',
        'etat_civil_emprunteur',
        'anciennete_emprunteur',
        'nom_conjoint_emprunteur',
        'telephone_conjoint',
        'lieu_travail_conjoint',
        'employeur_conjoint',
        'Anciennete_conjoint',
        'personne_reference',
        'lieu_perso_ref',
        'tel_perso_ref',
        'activite1',
        'activite2',
        'activite3',
        'faiblesses_contraintes_emprunteur_marche_approvisionnement',
        'forces_Strategies_envisagees_par_emprunteur',
        'source_revenus1',
        'montant_source_revenus1',
        'objet_depense1',
        'montant_objet_depense1',
        'source_revenus2',
        'montant_source_revenus2',
        'objet_depense2',
        'montant_objet_depense2',
        'source_revenus3',
        'montant_source_revenus3',
        'objet_depense3',
        'montant_objet_depense3',
        'source_revenus4',
        'montant_source_revenus4',
        'objet_depense4',
        'montant_objet_depense4',
        'flexRadio1',
        'versement_jour',
        'versement_hebdo',
        'versement_mois',
        'versement_trimestre',
        'versement_semestre',
        'nombre_adhesion',
        'volume_adhesion',
        'credit',
        'pourquoi_credit',
        'nombre_credit',
        'date_dernier_credit',
        'montant_credit1',
        'date_credit1',
        'institution1',
        'penalites_payees1',
        'montant_credit2',
        'date_credit2',
        'institution2',
        'penalites_payees2',
        'montant_credit3',
        'date_credit3',
        'institution3',
        'penalites_payees3',
        'montant_credit4',
        'date_credit4',
        'institution4',
        'penalites_payees4',
        'type_credit_demande',
        'detail_objet_precision_activite',
        'cni_montant_demande',
        'date_demande',
        'condition_demande',
        'periodicite',
        'garantie_propose1',
        'nom_prenom_avaliseur',
        'residence',
        'cni',
        'telephone',
        'numero_compte',
        'activite_principale',
        'element_dossier',
        'commentaire_agent_demande',
        'commentaire_agent_rentabilite',
        'mode_description1',
        'valeur_garantie1',
        'combien_km_agence1',
        'doc_materiel_garantie1',
        'valeur_retenu_visiste1',
        'mode_description2',
        'valeur_garantie2',
        'combien_km_agence2',
        'doc_materiel_garantie2',
        'valeur_retenu_visiste2',
        'mode_description3',
        'valeur_garantie3',
        'combien_km_agence3',
        'doc_materiel_garantie3',
        'valeur_retenu_visiste3',
        'mode_description4',
        'valeur_garantie4',
        'combien_km_agence4',
        'doc_materiel_garantie4',
        'valeur_retenu_visiste4',
        'mode_description5',
        'valeur_garantie5',
        'combien_km_agence5',
        'doc_materiel_garantie5',
        'valeur_retenu_visiste5',
        'mode_description6',
        'valeur_garantie6',
        'combien_km_agence6',
        'doc_materiel_garantie6',
        'valeur_retenu_visiste6',
        'montant_credit_autorise',
        'commentaires',

        'proposition_agent_credit',
        'montant_propose_agent_credit',
        'type_credit_agent_credit',
        'taux_agent_credit',
        'nantissement_agent_credit',
        'garantie_agent_credit',
        'assurance_agent_credit',
        'versement_initial_agent_credit',
        'duree_agent_credit',
        'periodicite_agent_credit',
        'periode_de_grace_agent_credit',
        'commentaire_agent_credit',
        'nom_et_prenom_agent_credit',


        'avis_commentaire_credit_comite',
        'montant_propose_comite',
        'type_credit_comite',
        'taux_comite',
        'nantissement_com',
        'garantie_comite',
        'assurance_comite',
        'versement_initial_comite',
        'duree_comite',
        'periodicite_comite',
        'periode_de_grace_comite',
        'commentaire_avis_credit',
        'nom_et_prenom_credit',

    ];
        
    
} 
