<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Model;

class Credit extends Model
{

    protected $fillable = [
        'code_client',
        'num_account',
        'num_dossier',
        'montant_demande',
        'montant_octroye',
        'montant_debourse',
        'date',
        'date_demande',
        'date_complete_demande',
        'dossier_complete',
        'etat_credit',
        'duree',
        'duree_restant',
        'capital_rembourse',
        'interet_rembourse',
        'garantie_rembourse',
        'penalite_rembourse',
        'total_rembourse',
        'capital_du',
        'interet_restant_du',
        'montant_provision',
        'type_credit_id',
        'type_bien_id',
        'compte_comptable_id',
        'statut',
        'obj_dem',
        'detail_obj_dem',
        'date_etat',
        'motif',
        'delai_grac',
        'differe_jours',
        'prelev_auto',
        'nouv_duree_mois',
        'terme',
        'date_approbation',
        'date_deblocage',
        'date_provision',
        'suspension_pen',
        'nbre_reechelon',
        'details_motif',
        'prelev_commission',
        'commission',
        'assurance',
        'mnt_frais_doss',
        'taux_interet',
        'gar_num',
        'garantie_attendu',
        'type_garantie',
        'gar_tot_mobilise',
        'gar_num_mobilise',
        'gar_materielle',
        'gar_materielle_mobilise',
        'num_cre',
        'etat_gar',
        'cre_etat',
        'cre_date_etat',
        'perte_capital',
        'cre_retard_etat_max',
        'cre_retard_etat_max_jour',
        'cpt_prelev_frais',
        'description_gar_mobilise',
        'user_id',
        'user_complete_dossier',
        'avis_agent_credit',
        'avis_direction',
        'avis_ca',
    ];



}

