<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Type_credits extends Model
{
    use HasFactory;

    protected $fillable = [ 
        'name',
        'taux',
        'mnt_min',
        'mnt_max',
        'mode_calc_int',
        'mode_perc_int',
        'duree_min_mois',
        'duree_max_mois',
        'periodicite',
        'mnt_frais',
        'mnt_commission',
        'prc_assurance',
        'prc_gar_num',
        'prc_gar_mat',
        'prc_gar_tot',
        'prc_gar_encours',
        'mnt_penalite_jour',
        'prc_penalite_retard',
        'delai_grace_jour',
        'differe_jours_max',
        'nbre_reechelon_auth',
        'prc_commission',
        'type_duree_credit',
        'approbation_obli',
        'typ_pen_pourc_dcr',
        'cpte_cpta_prod_cr_int',
        'cpte_cpta_prod_cr_gar',
        'cpte_cpta_prod_cr_pen',
        'devise',
        'differe_ech_max',
        'freq_paiement_cap',
        'max_jours_compt_penalite',
        'gs_cat',
        'id_ag',
        'prelev_frais_doss',
        'percep_frais_com_ass',
        'differe_epargne_nantie',
        'report_arrondi',
        'calcul_interet_differe',
        'ordre_remb',
        'remb_cpt_gar',
        'mnt_assurance',
        'is_produit_decouvert',
        'prc_frais',
        'cpte_cpta_att_deb',
        'is_produit_actif',
        'taux_frais_lcr',
        'taux_min_frais_lcr',
        'taux_max_frais_lcr',
        'duree_nettoyage',
        'ordre_remb_lcr',
        'cpte_cpta_prod_cr_frais',
        'nb_jr_bloq_cre_avant_ech_max',
        'is_flexible',
        'is_taux_mensuel',
        'appl_interet_diff_echeance',
        'is_mobile_lending_credit',
        'prelev_garanti',
        'comptable_assurance',
        'precision_devise_credit',
        'appro_crdt_palier',
        'premier_credit_gratuit',
        'is_remboursement_anticipe',
        'date_creation',
        'date_modification',
        'comptable_commission',
    ];
}
